- Bit
- 4 Bits = Nibble
- 8 Bits = Byte
- 1024 Byte = KB
- 1024 KB = MB
- 1024 MB = GB ...

#Numpy

Numerical Python, used mosty for working with arrays. 

In [1]:
import numpy as np

In [2]:
np.__version__

'1.19.5'

##Creating a numpy array

syntax
```
arrayName = numpy.array(list to be converted to a array);
```

In [3]:
N = [1,2,3,4,5,6,7,8,9,10]
print(type(N), N)

n = np.array(N)
print(type(n), n)

<class 'list'> [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
<class 'numpy.ndarray'> [ 1  2  3  4  5  6  7  8  9 10]


##Array Dimentions


- 0 Dimention Array: a single elment
- 1 Dimention Array: when you have multiple elments in the array
- 2 Dimention Array: when you have another array inside an array
- 3 ...
- 4 ...
- ...

use ndim attribute to get the dimention of any array

syntax:
```
arrayName.ndim
```

In [4]:
zero = np.array(0)
one = np.array([0,1,2,3,4])
two = np.array([
                [0,1,2,3,4],
                [5,6,7,8,9],
                [10,11,12,13,14],
                [15,16,17,18,19]
])
three = np.array([
                  [[0,1], [2,3]],
                  [[4,5],[6,7]],
                  [[8,9],[10,11]]
])

In [5]:
print("Zero Dimention Array")
print(zero)
print("One Dimention Array")
print(one)
print("Two Dimention Array")
print(two)
print("Three dimention Array")
print(three)

Zero Dimention Array
0
One Dimention Array
[0 1 2 3 4]
Two Dimention Array
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Three dimention Array
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [6]:
print(zero.ndim)
print(one.ndim)
print(two.ndim)
print(three.ndim)

0
1
2
3


##Accessing these array elements - Indexing

every element has a index and the indexing starts with 0

In [7]:
print("accessing eleming in a zero dimention array")
print(zero)
print("accessing eleming in a one dimention array")
print(one[2], one[3])
print("accessing eleming in a two dimention array")
print(two[0], two[3])
print(two[0, 2], two[3, 3])
print("accessing eleming in a three dimention array")
print(three[0, 1, 0])
print(three[2, 0, 1])

accessing eleming in a zero dimention array
0
accessing eleming in a one dimention array
2 3
accessing eleming in a two dimention array
[0 1 2 3 4] [15 16 17 18 19]
2 18
accessing eleming in a three dimention array
2
9


In [8]:
print("Negative Indexing")
print(two[0, -1])
print(three[-2,-1,-2])

Negative Indexing
4
6


##Slicing arrays

In [9]:
print("Slicing a One Dimentional Array")
print(one[3:])
print("\nSlicing a Two Dimentional Array")
print(two[2:])
print(two[2:, -3:])
print("\nSlicing a Three Dimentional Array")
print(three[-2:])
print("")
print(three[-2:, -1])
print("")
print(three[-2:, -1, ::-1])

Slicing a One Dimentional Array
[3 4]

Slicing a Two Dimentional Array
[[10 11 12 13 14]
 [15 16 17 18 19]]
[[12 13 14]
 [17 18 19]]

Slicing a Three Dimentional Array
[[[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]

[[ 6  7]
 [10 11]]

[[ 7  6]
 [11 10]]


In [10]:
print(three[::-1, ::-1, ::-1])

[[[11 10]
  [ 9  8]]

 [[ 7  6]
  [ 5  4]]

 [[ 3  2]
  [ 1  0]]]


## Data types
- i: integer
- b: boolean
- u: unsigned integer
- f: float
- c: complex float
- m: timedelta
- M: datetime
- O: object
- S: string 
- U: unicode string 
- V: fixed chunk of memory for other types. 

In [12]:
print(type(two))
print(two.dtype)

<class 'numpy.ndarray'>
int64


In [13]:
week = np.array(['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'])

print(week.dtype)

<U9


In [14]:
print(zero.dtype)
print(one.dtype)
print(two.dtype)
print(three.dtype)

int64
int64
int64
int64


In [15]:
zero = np.array(0, dtype = 'i4')
one = np.array([0,1,2,3,4], dtype='i4')
two = np.array([
                [0,1,2,3,4],
                [5,6,7,8,9],
                [10,11,12,13,14],
                [15,16,17,18,19]
], dtype='i4')
three = np.array([
                  [[0,1], [2,3]],
                  [[4,5],[6,7]],
                  [[8,9],[10,11]]
], dtype='i4')

In [16]:
print(zero.dtype)
print(one.dtype)
print(two.dtype)
print(three.dtype)

int32
int32
int32
int32


In [17]:
print(zero)
print(one)
print(two)
print(three)

0
[0 1 2 3 4]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [18]:
N = np.array([1,2,3,4,5,6,7,8,9,10], dtype='U')
print(N)

['1' '2' '3' '4' '5' '6' '7' '8' '9' '10']


##Copy & View

Copy creates a diffrent copy of the given array and changing any of the arrys will not affect the other array

view does not own the data and any changes made to either of the arrays, the values will be changed in both the arrays

In [23]:
N = [1,2,3,4,5,6,7,8,9,10]
print('N:',N)

anotherN = N
print('anotherN:', anotherN)

anotherN[4]= 15
N[9] = 100

print('N:',N)
print('anotherN:', anotherN)

N: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
anotherN: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
N: [1, 2, 3, 4, 15, 6, 7, 8, 9, 100]
anotherN: [1, 2, 3, 4, 15, 6, 7, 8, 9, 100]


In [24]:
N = [1,2,3,4,5,6,7,8,9,10]
print('N:',N)

anotherN = N[:]
print('anotherN:', anotherN)

anotherN[4]= 15
N[9] = 100

print('N:',N)
print('anotherN:', anotherN)

N: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
anotherN: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
N: [1, 2, 3, 4, 5, 6, 7, 8, 9, 100]
anotherN: [1, 2, 3, 4, 15, 6, 7, 8, 9, 10]


###Copy array


In [27]:
oneCopy = one.copy()
print(oneCopy)
oneCopy[3] = 123
print("")
print(one)
print(oneCopy)

[0 1 2 3 4]

[0 1 2 3 4]
[  0   1   2 123   4]


###View array

In [28]:
oneView = oneCopy.view()
print('oneView:',oneView)
print('oneCopy:',oneCopy)

oneCopy[3] = 3
oneView[-1] = 40


print('oneView:',oneView)
print('oneCopy:',oneCopy)
print('one:', one)

oneView: [  0   1   2 123   4]
oneCopy: [  0   1   2 123   4]
oneView: [ 0  1  2  3 40]
oneCopy: [ 0  1  2  3 40]
one: [0 1 2 3 4]


Print the value of the base attribute
- copy return None
- view returns the original array

In [29]:
print(oneView.base)
print(oneCopy.base)

[ 0  1  2  3 40]
None


##Shape of a numpy array

the shape of an array is the number of elements in each dimension.

In [32]:
print(zero.shape)
print(one.shape)
print(two.shape)
print(three.shape)

()
(5,)
(4, 5)
(3, 2, 2)


##Reshape array

reshaping means changing the shape of an array


In [55]:
arr = np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print("Array with shape (2,8)")
print(arr.reshape(2,8))
print("\nArray with shape (4,4)")
print(arr.reshape(4,4))
print("\nArray with shape (2,4,2)")
print(arr.reshape(2,4,2))
print("\nArray with shape (4,2,2)")
print(arr.reshape(4,2,2))
print("\nArray with shape (2,1,2,4)")
print(arr.reshape(2,1,2,4))

Array with shape (2,8)
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]

Array with shape (4,4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Array with shape (2,4,2)
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]]

Array with shape (4,2,2)
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]]

Array with shape (2,1,2,4)
[[[[ 0  1  2  3]
   [ 4  5  6  7]]]


 [[[ 8  9 10 11]
   [12 13 14 15]]]]


In [58]:
print("\nArray with shape (4,the rest)")
print(arr.reshape(4,-1))
print("\nArray with shape (2, don't know, 8)")
print(arr.reshape(2,-1,8))


Array with shape (4,the rest)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Array with shape (2, don't know, 8)
[[[ 0  1  2  3  4  5  6  7]]

 [[ 8  9 10 11 12 13 14 15]]]


In [66]:
randomArray = np.array([
        [0,1,2,3,4],
        [5,6,7,8,9,10,11]
])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  This is separate from the ipykernel package so we can avoid doing imports until


In [67]:
print(randomArray)

[list([0, 1, 2, 3, 4]) list([5, 6, 7, 8, 9, 10, 11])]


In [68]:
print(randomArray.reshape(2,3,2))

ValueError: ignored

In [71]:
randomArray[0][2]

2